#!/bin/sh

if [ -f Makefile ]; then
    echo "uhh... Makefile already exists, you probably don't want to overwrite it" >&2
    exit 1
fi

cat >Makefile <<EOL
CC=gcc -Werror -Wall -Wextra -g -fsanitize=address,undefined,leak

main: main.c
	\$(CC) -o main main.c

clean:
	rm main
EOL
