#!/bin/sh

# TODO this only works with bash, why? why is echo broken with sh? I'm seeing a
# literal "-en" in the output because of the echo -en commands

# vim: ft=sh

if [ -f Makefile ]; then
    echo "uhh... Makefile already exists, you probably don't want to overwrite it" >&2
    exit 1
fi

cat >Makefile <<EOL
CC=gcc -Werror -Wall -Wextra -g -fsanitize=address,undefined,leak

main: main.c
	\$(CC) -o main main.c

clean:
	rm main
EOL
