#!/bin/sh

# text to speech

if [ $# -eq 0 ]; then
    echo "Expected text to tts-ify" >&2
    return 1
fi
ttsfile='/tmp/ttsfile.wav'
pico2wave --wave="$ttsfile" "$@" # (pico2wave is in debian package libttspico-utils)
aplay "$ttsfile"
rm --force "$ttsfile"
